Set up Rspec
CraftAcademy/prestige_worldwide pull request #2
Opened 2019-10-07 16:02 UTC by shsteindorsson

Set up Rspec
==========
[PT-link](https://www.pivotaltracker.com/story/show/168979336)

## PR content
In this PR we are adding Rspec to the project along with necessary gems.

## This PR contains:
- `rspec-rails` gem
- `shoulda-matchers` gem
- `pry-rails` gem
- `factory_bot_rails` gem

2019-10-07 16:05 UTC, DIzosimov approved these changes

2019-10-07 16:06 UTC, clalil approved these changes

2019-10-07 16:08 UTC, lucamarial approved these changes

2019-10-07 16:08 UTC, ghost approved these changes

2019-10-07 16:30 UTC, miyeaier approved these changes

2019-10-08 07:20 UTC, faraznaeem requested changes

2019-10-08 07:20 UTC, faraznaeem commented on config/application.rb
> +    config.load_defaults 6.0
This line should be before the generators

2019-10-08 07:41 UTC, ghost approved these changes

2019-10-08 07:44 UTC, miyeaier approved these changes

2019-10-08 07:49 UTC, DIzosimov approved these changes

2019-10-08 07:57 UTC, faraznaeem approved these changes

2019-10-08 07:57 UTC, merged