[WIP] Add drink list feature and required step definitions.
CraftAcademy/prestige_worldwide pull request #4
Opened 2019-10-08 08:14 UTC by clalil

2019-10-08 09:47 UTC, ghost approved these changes

2019-10-09 08:02 UTC, faraznaeem commented
Is this feature still WIP

2019-10-09 14:25 UTC, miyeaier approved these changes

2019-10-09 14:34 UTC, shsteindorsson approved these changes

2019-10-09 14:35 UTC, DIzosimov approved these changes

2019-10-09 17:09 UTC, oliverochman requested changes

2019-10-09 17:09 UTC, oliverochman commented on config/routes.rb
>    root controller: :welcome, action: :index
why do you have this route?

2019-10-09 17:09 UTC, oliverochman commented on features/search_for_cocktails.feature
> +    Given I am on the cocktail page
Can the user get to this page if he visits the root_path first?

2019-10-09 17:09 UTC, oliverochman commented on features/search_for_cocktails.feature
> +    Given I am on the cocktail page
Please add a background where you say where the user is instead of repeating this step in two scenarios

2019-10-09 17:09 UTC, oliverochman commented on features/search_for_cocktails.feature
> +    And I fill in 'Search' with 'Gin'
`When I fill in 'Search' with 'Gin'`

2019-10-09 17:20 UTC, clalil commented on config/routes.rb
>    root controller: :welcome, action: :index
Originally, me and Luca created a root controller for the cocktail page. This is the route that was merged from the guy's previous PR. Since our root controller's overlapped we kept theirs since ours could just be used as a resource.

2019-10-09 17:23 UTC, clalil commented on features/search_for_cocktails.feature
> +    Given I am on the cocktail page
Not unless he knows which route to manually pass into the url. This page will be available later only once you've signed in and paid.

2019-10-09 17:25 UTC, clalil commented on features/search_for_cocktails.feature
> +    And I fill in 'Search' with 'Gin'
Changed accordingly.

2019-10-09 17:25 UTC, clalil commented on features/search_for_cocktails.feature
> +    Given I am on the cocktail page
Changed accordingly.

2019-10-09 17:28 UTC, oliverochman commented on config/routes.rb
>    root controller: :welcome, action: :index
The main functionality of the app is this feature.
Does the other welcome controller have any functionality?

2019-10-09 17:29 UTC, oliverochman commented on features/search_for_cocktails.feature
> +    Given I am on the cocktail page
Premature optimization, please make the cocktail index action the root_path

2019-10-09 17:30 UTC, clalil commented on config/routes.rb
>    root controller: :welcome, action: :index
Not that I am aware of. But I thought we always had to have a root controller for at least the main page?

2019-10-09 17:31 UTC, clalil commented on features/search_for_cocktails.feature
> +    Given I am on the cocktail page
But our cocktail page is on the cocktails_path and not on the welcome_path...

2019-10-09 18:06 UTC, oliverochman commented on app/views/cocktails/index.html.haml
> +%h1 Search for your drink of choice:
shouldn't this be underneath the title at line 13

2019-10-09 18:10 UTC, clalil commented on app/views/cocktails/index.html.haml
> +%h1 Search for your drink of choice:
Changed accordingly.

2019-10-09 18:11 UTC, oliverochman approved these changes

2019-10-09 18:11 UTC, merged