[WIP] Welcome to Prestige
CraftAcademy/prestige_worldwide pull request #5
Opened 2019-10-08 09:45 UTC by DavveDavve

[PT-Link](https://www.pivotaltracker.com/story/show/168988777)

# PR Content
- Welcome page feature test
- Basic step definitions
- Assertion step definitions

## What I have Learned

2019-10-08 09:46 UTC, ghost approved these changes

2019-10-08 14:10 UTC, ghost approved these changes

2019-10-08 16:04 UTC, miyeaier approved these changes

2019-10-09 07:31 UTC, shsteindorsson approved these changes

2019-10-09 07:32 UTC, faraznaeem requested changes
Preferrably in the future you can add the styling gem as a separate chore and PR, as that is needed throughout the application

2019-10-09 07:32 UTC, faraznaeem commented on app/views/layouts/_nav.html.haml
> +      -# %a.block.mt-4.lg:inline-block.lg:mt-0.text-teal-200.hover:text-white.mr-4{:href => root_path}
Please clean out the comments

2019-10-09 07:32 UTC, faraznaeem commented on app/views/layouts/application.html.haml
> +    = stylesheet_pack_tag 'application'
Please use new ruby syntax and not hash rockets `=>`

2019-10-09 07:32 UTC, faraznaeem commented on app/views/welcome/index.html.haml
> +  %img.w-full{:alt => "Sunset in the mountains", :src => "http://fusioncoedsoccer.com/media/bearleague/bl1477363156652.png"}/
Please use new ruby syntax and not hash rockets `=>`

2019-10-09 10:15 UTC, DavveDavve commented on app/views/layouts/_nav.html.haml
> +      -# %a.block.mt-4.lg:inline-block.lg:mt-0.text-teal-200.hover:text-white.mr-4{:href => root_path}
Will do :)

2019-10-09 10:17 UTC, DavveDavve commented on app/views/layouts/application.html.haml
> +    = stylesheet_pack_tag 'application'
Donezo :)

2019-10-09 10:17 UTC, DavveDavve commented on app/views/welcome/index.html.haml
> +  %img.w-full{:alt => "Sunset in the mountains", :src => "http://fusioncoedsoccer.com/media/bearleague/bl1477363156652.png"}/
Donezo :)

2019-10-09 10:26 UTC, shsteindorsson approved these changes

2019-10-09 10:53 UTC, faraznaeem approved these changes

2019-10-09 11:17 UTC, faraznaeem requested changes

2019-10-09 11:17 UTC, faraznaeem commented on features/welcome_page.feature
> +  When I visit the landing page
this user story is totally off
```
As a user
In order to learn about the offerings 
I would like to learn more about the app 
```

2019-10-09 11:18 UTC, faraznaeem approved these changes

2019-10-09 11:18 UTC, merged