User can login
CraftAcademy/prestige_worldwide pull request #8
Opened 2019-10-09 14:20 UTC by DavveDavve

[PT-Link](https://www.pivotaltracker.com/story/show/169035279)

# PR Content
- Adds login feature test
- Adds step definitions for login feature test

## What I have learned

2019-10-09 16:52 UTC, clalil commented on app/views/layouts/application.html.haml
> +    -#.bg-blue-100.border-t.border-b.border-blue-500.text-blue-700.px-4.py-3{role: "alert"}
Please remove commented out styling.

2019-10-09 19:01 UTC, DavveDavve commented on app/views/layouts/application.html.haml
> +    -#.bg-blue-100.border-t.border-b.border-blue-500.text-blue-700.px-4.py-3{role: "alert"}
Done :)

2019-10-09 20:13 UTC, shsteindorsson approved these changes

2019-10-10 07:49 UTC, oliverochman requested changes

2019-10-10 07:49 UTC, oliverochman commented on app/helpers/application_helper.rb
> +      when :error then "alert alert-error"
what's the difference between line 6 and 7

2019-10-10 07:49 UTC, oliverochman commented on app/views/cocktails/index.html.haml
> +          Login button
why do you still have this login paragraph?

2019-10-10 07:49 UTC, oliverochman commented on app/views/devise/registrations/new.html.haml
> +      = f.label :password
have you modified this file?

2019-10-10 07:49 UTC, oliverochman commented on app/views/devise/sessions/new.html.haml
> +      = f.label :email
same here

2019-10-10 07:49 UTC, oliverochman commented on app/views/devise/shared/_links.html.haml
> +    = link_to "Log in", new_session_path(resource_name)
same here

2019-10-10 07:49 UTC, oliverochman commented on features/login.feature
> +    Scenario: User logs in successfully [Happy path]
indent everything from line 12 down back one time

2019-10-10 07:53 UTC, DIzosimov commented on app/helpers/application_helper.rb
> +      when :error then "alert alert-error"
guess we can remove line 7?

2019-10-10 07:54 UTC, DavveDavve commented on app/views/cocktails/index.html.haml
> +          Login button
Is there any reason why we should remove this paragraph?

2019-10-10 07:55 UTC, DavveDavve commented on app/views/devise/registrations/new.html.haml
> +      = f.label :password
We had to use it for styling, with the .main tag at the top otherwise it was inaccessible to style the h2 and the signup button

2019-10-10 07:55 UTC, DavveDavve commented on app/views/devise/sessions/new.html.haml
> +      = f.label :email
same reason as the one above.

2019-10-10 07:56 UTC, DIzosimov commented on app/views/devise/shared/_links.html.haml
> +    = link_to "Log in", new_session_path(resource_name)
we needed this to remove the unecessary links like forgot password that were out of scope and didnt have code to support it.

2019-10-10 07:56 UTC, DavveDavve commented on features/login.feature
> +    Scenario: User logs in successfully [Happy path]
ok :)

2019-10-10 11:55 UTC, merged